### ISSUE TITLE
DB Schema

### ISSUE THREAD

**Issue by claire-kz** [bfriel/Cycl#5]
- Routes: what is `route_positions`?  Should it be of type text?
- Remove the word `route` before anything in the `route` table
- Don't use the word `route`.  I think it is a reserved word in Ruby.  Change it everywhere in your code.  Suggestions include: `tracks`, `circuits`, `trails`, `course` 
- Followers: add to description that columns reference users table 
- Comments: change content column type to text

**Comment by bfriel** [comment]
I'm imaging ride_positions to be an array of arrays -- each subarray holding a pair of coordinates for a given waypoint on the map. For simplicities sake, I was thinking of wrapping this giant array in " " and making it type text. Example:
"[[37.71111, -122.41111], [37.72222, -122.42222], [37.73333, -122.43333]]"
